#ifndef __OK_CMD_PROTOCOL_H__
#define __OK_CMD_PROTOCOL_H__

#include <stdint.h>

// refer https://onekeyhq.atlassian.net/wiki/spaces/ONEKEY/pages/106790964/Touch for details
// main command definitions
typedef enum {
    // ble-mcu -> stm-mcu
    OK_DOWNLINK_MAIN_CMD_START           = 0x00,
    OK_DOWNLINK_MAIN_CMD_ADV_NAME        = 0x01,
    OK_DOWNLINK_MAIN_CMD_BLE_STATUS      = 0x02,
    OK_DOWNLINK_MAIN_CMD_BLE_PAIR_CODE   = 0x03,
    OK_DOWNLINK_MAIN_CMD_BLE_PAIR_STATUS = 0x04,
    OK_DOWNLINK_MAIN_CMD_FW_VERSION      = 0x05,
    OK_DOWNLINK_MAIN_CMD_SD_VERSION      = 0x06,
    OK_DOWNLINK_MAIN_CMD_BOOT_VERSION    = 0x07,
    OK_DOWNLINK_MAIN_CMD_POWER_MANAGE    = 0x08,
    OK_DOWNLINK_MAIN_CMD_POWER_PERCENT   = 0x09,
    OK_DOWNLINK_MAIN_CMD_BUTTON_EVENT    = 0x0A,
    OK_DOWNLINK_MAIN_CMD_SYS_POWER       = 0x0B,
    OK_DOWNLINK_MAIN_CMD_FLASHLED_CTRL   = 0x0C,
    OK_DOWNLINK_MAIN_CMD_BAT_INFO        = 0x0D,
    OK_DOWNLINK_MAIN_CMD_SIGN            = 0x0E,
    OK_DOWNLINK_MAIN_CMD_BUILD_ID        = 0x10,
    OK_DOWNLINK_MAIN_CMD_HASH            = 0x11,
    OK_DOWNLINK_MAIN_CMD_BLE_MAC         = 0x12,

    // stm-mcu -> ble-mcu
    OK_UPLINK_MAIN_CMD_BLE_CTRL   = 0x81,
    OK_UPLINK_MAIN_CMD_POWER_CTRL = 0x82,
    OK_UPLINK_MAIN_CMD_BLE_INFO   = 0x83,
    OK_UPLINK_MAIN_CMD_RESET      = 0x84,
    OK_UPLINK_MAIN_CMD_FLASHLED   = 0x85,
    OK_UPLINK_MAIN_CMD_BAT_STATUS = 0x86,
    OK_UPLINK_MAIN_CMD_SIGN       = 0x87,
} ok_main_cmd_e;

// sub command definitions
typedef enum {
    OK_SUB_CMD_COMMON_DEFAULT = 0x00,
    OK_SUB_CMD_COMMON_1       = 0x01,
    OK_SUB_CMD_COMMON_2       = 0x02,
    OK_SUB_CMD_COMMON_3       = 0x03,
    OK_SUB_CMD_COMMON_4       = 0x04
} ok_sub_cmd_comm_e;

// downlink sub command definitions
// @OK_DOWNLINK_MAIN_CMD_BLE_STATUS
enum {
    OK_DOWNLINK_SUB_CMD_BLE_CONNECTED    = 0x01,
    OK_DOWNLINK_SUB_CMD_BLE_DISCONNECTED = 0x02,
    OK_DOWNLINK_SUB_CMD_BLE_TURN_ON      = 0x03,
    OK_DOWNLINK_SUB_CMD_BLE_TURN_OFF     = 0x04,
};

// @OK_DOWNLINK_MAIN_CMD_BLE_PAIR_STATUS
enum {
    OK_DOWNLINK_SUB_CMD_BLE_PAIR_SUCCESS = 0x01,
    OK_DOWNLINK_SUB_CMD_BLE_PAIR_FAILED  = 0x02,
};

// @OK_DOWNLINK_MAIN_CMD_POWER_MANAGE
enum {
    OK_DOWNLINK_SUB_CMD_POWER_CONNECT    = 0X01,
    OK_DOWNLINK_SUB_CMD_POWER_DISCONNECT = 0x02,
    OK_DOWNLINK_SUB_CMD_POWER_CHARGING   = 0x03,
    OK_DOWNLINK_SUB_CMD_POWER_CHARGED    = 0x04,
};

// @OK_DOWNLINK_MAIN_CMD_BUTTON_EVENT
enum {
    OK_DOWNLINK_MAIN_CMD_BUTTON_SHORT_PRESS = 0x01,
    OK_DOWNLINK_MAIN_CMD_BUTTON_LONG_PRESS  = 0x02,
    OK_DOWNLINK_MAIN_CMD_BUTTON_KEEP_PRESS  = 0x03,
    OK_DOWNLINK_MAIN_CMD_BUTTON_RELEASE     = 0x04,
};

// OK_DOWNLINK_MAIN_CMD_SYS_POWER
enum {
    OK_DOWNLINK_MAIN_CMD_SYS_POWER_OFF  = 0x01,
    OK_DOWNLINK_MAIN_CMD_EMMC_POWER_OFF = 0x02,
    OK_DOWNLINK_MAIN_CMD_EMMC_POWER_ON  = 0x03,
};

// uplink sub command definitions
// @OK_UPLINK_MAIN_CMD_BLE_CTRL
enum {
    OK_UPLINK_SUB_CMD_BLE_TURN_ON    = 0x01,
    OK_UPLINK_SUB_CMD_BLE_TURN_OFF   = 0x02,
    OK_UPLINK_SUB_CMD_BLE_DISCONNECT = 0x03,
    OK_UPLINK_SUB_CMD_BLE_GET_STATUS = 0x04,
};

// @OK_UPLINK_MAIN_CMD_POWER_CTRL
enum {
    OK_UPLINK_SUB_CMD_SYS_POWER_TURN_OFF   = 0x01,
    OK_UPLINK_SUB_CMD_EMMC_POWER_TURN_OFF  = 0x02,
    OK_UPLINK_SUB_CMD_EMCC_POWER_TURN_ON   = 0x03,
    OK_UPLINK_SUB_CMD_POWER_PERCENT_GET    = 0x04,
    OK_UPLINK_SUB_CMD_USB_POWER_STATUS_GET = 0x05,
    OK_UPLINK_SUB_CMD_CHARGE_ENABLE        = 0x06,
    OK_UPLINK_SUB_CMD_CHARGE_DISABLE       = 0x07,
};

// @OK_UPLINK_MAIN_CMD_BLE_INFO
enum {
    OK_UPLINK_SUB_CMD_BLE_ADV_NAME_GET     = 0x01,
    OK_UPLINK_SUB_CMD_BLE_FIRMWARE_VER_GET = 0x02,
    OK_UPLINK_SUB_CMD_BLE_SD_VER_GET       = 0x03,
    OK_UPLINK_SUB_CMD_BLE_BOOT_VER_GET     = 0x04,
    OK_UPLINK_SUB_CMD_BLE_BUILD_ID_GET     = 0x05,
    OK_UPLINK_SUB_CMD_BLE_HASH_GET         = 0x06,
    OK_UPLINK_SUB_CMD_BLE_MAC_GET          = 0x07,
};

// @OK_UPLINK_MAIN_CMD_FLASHLED
enum {
    OK_UPLINK_SUB_CMD_FLASHLED_SET = 0x01,
    OK_UPLINK_SUB_CMD_FLASHLED_GET = 0x02,
};

// @OK_UPLINK_MAIN_CMD_BAT_STATUS
enum {
    OK_UPLINK_SUB_CMD_BAT_VOL               = 0x01,
    OK_UPLINK_SUB_CMD_BAT_CHARGE_CURRENT    = 0x02,
    OK_UPLINK_SUB_CMD_BAT_DISCHARGE_CURRENT = 0x03,
    OK_UPLINK_SUB_CMD_BAT_INNER_TEMP        = 0x04,
};

// @OK_UPLINK_MAIN_CMD_SIGN
enum {
    OK_UPLINK_SUB_CMD_BLE_PUBKEY       = 0x01,
    OK_UPLINK_SUB_CMD_BLE_PUBKEY_LOCK  = 0x02,
    OK_UPLINK_SUB_CMD_BLE_SIGN_REQUEST = 0x03,
};

void ok_cmd_parse(uint8_t *data, uint16_t length);

#endif // __OK_CMD_PROTOCOL_H__
